### ISSUE TITLE
trying to predict/avoid overwriting for staled/documentation table while developments/deployment tests

### ISSUE THREAD

**Issue by tuxun** [RELNO/CS_cityscopeJS_Scanner#11]
- the legotizer could ask if we are sure to want to overwrite an existing table when we load json?
goal: stop last impatients dataviz lovers with a last datalove warning ;)

**Comment by RELNO** [comment]
Sorry for being pedantic but it would help if we can have these issues broken down to separated ones.
As for the last point -- this might be a bit costly event, as it required `GET` of all table names, parse and match.

**Comment by tuxun** [comment]
first, the last point (because i like logic ;) ): couldnt the backend answer just answer "busy" instead of "ok" when a legotizer try to push a table with an already existing name? would it be that costly?

secondly, others points are now new issues

**Comment by RELNO** [comment]
This is how it's done in cityIO frontend: 

```
async function getTables() {
  infoDiv("Starting Applet Logger>>>");
  infoDiv("_________________________");

  let tableArray = [];
  let cityIOurl = "https://cityio.media.mit.edu/api/tables/list";
  const tables = await getCityIO(cityIOurl);

  infoDiv("Reading CityIO tables");

  for (let i = 0; i < tables.length; i++) {
    let thisTable = await getCityIO(tables[i]);
    infoDiv(
      i +
        " of " +
        tables.length +
        " tables: " +
        clearNames(tables[i]).link(tables[i]) +
        " || Remove Table".link(
          "https://cityio.media.mit.edu/api/table/clear/" +
            clearNames(tables[i])
        )
    );

    //check id API v2 [to replace with proper check later]
    if (thisTable.header) {
      thisTable = thisTable.header;
      tableArray.push({
        url: tables[i],
        name: thisTable.name,
        lat: thisTable.spatial.latitude,
        lon: thisTable.spatial.longitude
      });
    }
  }
  makeMap(tableArray);
}

```

Would you care testing this? I reckon this should be done as soon as the user load the local json file. Then, a prompt should force them to change the name and load again  [also, refresh CSjs] if their table name == cityIO active table. 
Therefore the checking function only run once per session, so not that costly.

**Comment by RELNO** [comment]
The key part here is of course:

```
let cityIOurl = "https://cityio.media.mit.edu/api/tables/list";
  const tables = await getCityIO(cityIOurl);
```

**Comment by tuxun** [comment]
You propose we check in the scanner that the table name dont already exist, making an async call, before pushing a new table.

I know that's what i asked, my problem to understand your point is: I after that, I was thinking to issue https://github.com/CityScope/CS_CityIO_Frontend/issues/8 , where my final thought (in my mind, maybe not yet in the post i made) was: 
what is the point to check in client if table name are "lowercase", given to be secure, we should test it again server side? 
server side proposal;
- when a legit client or whatever post a table: 
-- lowercase name entry server side, 
-- table name exist? accept post request; return http code smthing wrong (i'am teapot?)
Then in API when someone try to get a table,  lowercase the table name requested.

As this: all pushed table will be lowercase, all request will reach their base whatever the lowercaseing (<-thx ;) ), all duplicate string name will be rejected.
Oh, and in the scanner: in request is rejected, stop post and ask new name ;) 

STOP: we cant test if we would overwrite a table, cause that how we update them. 
I need a little pause ;)

**Comment by tuxun** [comment]
we would need a create api entry point?

**Comment by tuxun** [comment]
do you feel the uggly PR coming? :)

**Comment by tuxun** [comment]
@RELNO i have a problem of portability of variable: 
i try to  `var serverurl=value` in index.js  so we coud use this variable in both datgui.js  and module.js.

datgui.js: for make the "open on cityio" link
module.js: for ask twice if we want overwrite an existing table if its on mit cityio server, or once, if its just one of our existing table on OUR configured cityio server... 
It also should be used in the cityiopost() function (still in module.js) instead to have the hardcoded server url string multiple time on source code (and in multiple files)

Kinda... https://stackoverflow.com/questions/3922994/share-variables-between-files-in-node-js 
any good practice to recommend? Should I use a config object in storage or something like that?

**Comment by RELNO** [comment]
> @RELNO i have a problem of portability of variable:
i try to var serverurl=value in index.js so we coud use this variable in both datgui.js and module.js.
datgui.js: for make the "open on cityio" link
module.js: for ask twice if we want overwrite an existing table if its on mit cityio server, or once, if its just an existing table on OUR configured cityio server...
It also should be used in the cityiopost() function (still in module.js) instead to have the hardcoded server url string multiple time on source code (and in multiple files)
Kinda... https://stackoverflow.com/questions/3922994/share-variables-between-files-in-node-js
any good practice to recommend? Should I use a config module or something like that?


Currently, a [very dirty] Storage architecture is used for global vars, but it's very likely this would be dropped on future versions. But for now that's what we use. 

Also, following our discussion before, 'force lower case table name' is now implemented.

**Comment by RELNO** [comment]
closing for now. New cityIO features will probably include some of the above.
